### PR TITLE
Initial work on #14

### LINKED ISSUE #19: Failures in `test_noneuclidian_distance_calculation`
In #15 , I mentioned that there're some critical assertion failures, this is one of them.

For the corresponding code, please refer to https://github.com/utensil-contrib/galgebra/blob/14-pip/tests/test_test.py#L188-L287 .

Assertion failures are the following:

```py
>       assert str(W.simplify()) == '(X.Y)*C - (X.e)*(Y.e)*C + (X.e)*(Y.e) + S*sqrt((X.Y)**2 - 2*(X.Y)*(X.e)*(Y.e))'
E       AssertionError: assert 'sqrt((X.Y)*(...e)*(Y.e) + S)' == '(X.Y)*C - (X....*(X.e)*(Y.e))'
E         - sqrt((X.Y)*((X.Y) - 2*(X.e)*(Y.e)))*((1/B)*(X.Y)*C - (1/B)*(X.e)*(Y.e)*C + (1/B)*(X.e)*(Y.e) + S)
E         + (X.Y)*C - (X.e)*(Y.e)*C + (X.e)*(Y.e) + S*sqrt((X.Y)**2 - 2*(X.Y)*(X.e)*(Y.e))
```

```py
>       assert str(Wd_1) == '(X.e)*(Y.e)'
E       AssertionError: assert '(1/B)*(X.e)*...*(X.e)*(Y.e))' == '(X.e)*(Y.e)'
E         - (1/B)*(X.e)*(Y.e)*sqrt((X.Y)**2 - 2*(X.Y)*(X.e)*(Y.e))
E         + (X.e)*(Y.e)
```

```py
>       assert str(Wd_C) == '(X.Y) - (X.e)*(Y.e)'
E       AssertionError: assert '(1/B)*(X.Y)*...*(X.e)*(Y.e))' == '(X.Y) - (X.e)*(Y.e)'
E         - (1/B)*(X.Y)*sqrt((X.Y)**2 - 2*(X.Y)*(X.e)*(Y.e)) - (1/B)*(X.e)*(Y.e)*sqrt((X.Y)**2 - 2*(X.Y)*(X.e)*(Y.e))
E         + (X.Y) - (X.e)*(Y.e)
```

### LINKED ISSUE #20: Incorrect LaTeX output in `test_derivatives_in_spherical_coordinates`
The following problems are indicated by red arrows in the screenshots:

Broken integrity of greek letters:

image

`thetaphi` rendered to `\phi \phi`:

image

image

### PR DESCRIPTION
**Pull request by utensil**
This is the initial work on #14 . I'm opening this PR to discuss the partially completed code, please don't merge it yet.
- [x] write a `setup.py` so it can be installed by `python setup.py install`
- [x] add `.gitignore` and remove `.pyc` files
- [x] add option `--noconflict` to use `galgebra` as namespace
- [x] fix tests
- [x] fix #19 
- [x] fix #20
- [x] [upload `galgebra` to Test PyPI](https://packaging.python.org/tutorials/packaging-projects/)
- [x] upload `galgebra` to PyPI (done by hugohadfield, see https://pypi.org/project/galgebra/ )

### CODE REVIEW

**Comment by utensil** [comment]
@brombo I was busy in the last few weeks and have just finished the first pass of the tests. Except for the postpone ones (marked with `FIXME` in comment), all other tests are green.

Here's my workflow for verifying test cases:

1. add a `self` parameter to a test case
2. convert the construction part of the test case according to the corresponding function in `terminal_check.py`
3. run commands like `py.test tests/test_test.py::TestTest::test_reciprocal_frame_test` to verify the case
4. some assertions are failing, mostly because the way `sympy` or `galgebra` handles simplifications
5. [py.test](http://pytest.org/latest/getting-started.html#getstarted) presents the differences between the expected output and the actual ouput, I verify them by my own eyes and correct the assertions
6. compare test cases and `terminal_check.py` to see if there's anything missing

There're some critical issues with some of the outputs, I would investigate them later in other issues and PRs. I think this PR has reached a stage for reviewing and merging. Would you have time to take a look at the code?

**Comment by utensil** [comment]
@brombo Would you have time to take a look at the code? This PR and related issues are hanging around for a while.

**Comment by brombo** [comment]
On 06/25/2016 11:12 AM, Utensil Song wrote:
>
> @brombo <https://github.com/brombo> Would you have time to take a look 
> at the code? This PR and related issues are hanging around for a while.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/brombo/galgebra/pull/15#issuecomment-228549391>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AACzvXTp4ktL-0ocsJFfx5Sp9gPwURRpks5qPUVAgaJpZM4IkKyb>.
>
In test_test.py line 245 replace -

W = W.subs(1/Binv,Bmag)

with -

W = W.subs(Binv,1/Bmag)

that worked for me.

**Comment by brombo** [comment]
I have forgotten, please remind me what program do I use to run 
test_test.py?

**Comment by utensil** [comment]
> I have forgotten, please remind me what program do I use to run
> test_test.py?

Run `py.test tests/test_test.py` for the whole file and run something like `py.test tests/test_test.py::TestTest::test_reciprocal_frame_test` for one specific test case.

**Comment by utensil** [comment]
Or simply just run `python setup.py test`, it will run all test cases in `test_mv.py` and `test_test.py` and  output something like:

```
$ python setup.py test
running test
running egg_info
writing requirements to galgebra/galgebra.egg-info/requires.txt
writing galgebra/galgebra.egg-info/PKG-INFO
writing top-level names to galgebra/galgebra.egg-info/top_level.txt
writing dependency_links to galgebra/galgebra.egg-info/dependency_links.txt
reading manifest file 'galgebra/galgebra.egg-info/SOURCES.txt'
writing manifest file 'galgebra/galgebra.egg-info/SOURCES.txt'
running build_ext
test_blade_coefs (tests.test_mv.TestMv) ... ok
test_is_base (tests.test_mv.TestMv) ... ok
test_basic_multivector_operations (tests.test_test.TestTest) ... ok
test_check_generalized_BAC_CAB_formulas (tests.test_test.TestTest) ... ok
test_conformal_representations_of_circles_lines_spheres_and_planes (tests.test_test.TestTest) ... ok
test_derivatives_in_rectangular_coordinates (tests.test_test.TestTest) ... ok
test_derivatives_in_spherical_coordinates (tests.test_test.TestTest) ... ok
test_extracting_vectors_from_conformal_2_blade (tests.test_test.TestTest) ... ok
test_noneuclidian_distance_calculation (tests.test_test.TestTest) ... ok
test_properties_of_geometric_objects (tests.test_test.TestTest) ... ok
test_reciprocal_frame_test (tests.test_test.TestTest) ... ok
test_rounding_numerical_components (tests.test_test.TestTest) ... ok

----------------------------------------------------------------------
Ran 12 tests in 36.368s

OK
```

**Comment by utensil** [comment]
> In test_test.py line 245 replace -
> 
> W = W.subs(1/Binv,Bmag)
> 
> with -
> 
> W = W.subs(Binv,1/Bmag)
> 
> that worked for me.

Good catch! It worked. This will fix #19 .

**Comment by utensil** [comment]
#19 and #20 are now fixed and reflected in test cases.

**Comment by hugohadfield** [comment]
Ah fair enough! I think I already had a version of this up on Pypi with all the lingering pull requests merged in using my branch! Will have a look and see if I can find where I put it

**Comment by hugohadfield** [comment]
https://pypi.org/project/galgebra/

**Comment by utensil** [comment]
> I think I already had a version of this up on Pypi with all the lingering pull requests merged in using my branch! 

That's really great! Especially "with all the lingering pull requests merged in". But I made a comparison, it seems that this PR is not yet merged and there're some conflicts.

And also I wonder if it's appropriate for us to use the name galgebra on PyPI because it seems neither of us is related to or authorized by @brombo ? That's why I only upload it to the Test PyPI and stopped there.

>  I think the best thing would be for us to both work together on maintaining the package on a separate branch as it seems @brombo does not have much time any more?

I'm happy to join this effort. We could be more active in PR reviewing, merging, CI setup, document writing, test improvement etc. in a organization which could be named "galgebra-community".

> I cannot spend a huge amount of time on maintenance .....

Me too. But with both of us and possibly more to come, it would improve gradually and become a better library to "be really useful for the field".....

**Comment by utensil** [comment]
galgebra-community is created with issues enabled and you should receive the invitation by now with owner permission.

Also I've forked brombo/master@HEAD as a starting point, and we could send PRs to it and merge after some discussion? Does it sound ok to you?

**Comment by hugohadfield** [comment]
Yeah, I guess we should really define some project objectives to make sure we have similar ideas about how the library should go!

From my perspective I use this library for messing about with proofs and occasionally symbolic optimisation of algorithms for improved performance gaalop style. From that perspective I care about:
Having Travis testing setup - ensure correctness of library
Python 3 compatible
Compatible syntax with  https://github.com/pygae/clifford
Having good set of docs and notebooks to get started
Minimal dependencies/maximum portability

@arsenovic you might like to get involved in this as well if you have time? one option would be even to add it into https://github.com/pygae, what would you think of that @utensil ? Maybe worth organising a google hangout to discuss?

**Comment by utensil** [comment]
> one option would be even to add it into https://github.com/pygae, what would you think of that @utensil ?

Oh, I didn't noticed the organization (only starred gae/clifford some time ago). That's a better place to put the fork with a better name and it's more established and actively maintained if @arsenovic is ok.

Yeah, we share similar goals here: CI, py3, docs, notebooks, tests. Also I would like to help with a better environment for the community, like responding to issues, helping reviewing PRs and discussing a roadmap with users of this library and release versions on PyPI with release notes to make the community to use it with ease and some degree of insurance etc. because these are the foundations. I don't think we need a complete roadmap immediately (with specific functionalities) but laying the foundations for a possible one.

> Compatible syntax with https://github.com/pygae/clifford

Yes, clifford would be more powerful combined with galgebra, interoperability is the bridge . I tried clifford earlier [here](http://nbviewer.jupyter.org/github/utensil/julia-playground/blob/master/ConformalGeometricAlgebra.ipynb), trying to print it to LaTeX (which galgebra is already [capable](http://nbviewer.jupyter.org/github/utensil/julia-playground/blob/master/packages/galgebra.py.ipynb), though the code is not necessarily well structured and has some bugs, but it works) and possibly visualize (in simple scenarios).

> Minimal dependencies/maximum portability

There are two dependencies at this time: sympy and numpy, but it seems that numpy is not needed, than there would be only sympy left and is a hard dependency.

And what do you mean by maximum portability other than supporting both py2 and py3?

> Maybe worth organising a google hangout to discuss?

I'm probably not able to join a google hangout and more available in an async way of communicating (i.e. replying to issues or Gitter).

**Comment by hugohadfield** [comment]
> What features do you like most that are available in galgebra but clifford?
galgebra is good for me because it is symbolic, clifford is good for me because it is numerical.. when I want to prove something that I suspect to be true already (or would just like something to do some of the algebra and latex formatting for writing a paper :p) it is useful to have a symbolic package, when I want to build an algorithm for useful things I use clifford! So for me latex formatting of the numerical output of clifford is not important as its not really what I use it for, although it could well be a nice thing to incorporate as other users might like it..

By maximum portability I mean small number of dependencies that are part of the normal scientific python ecosystem (great that this only has sympy and numpy) and also importantly easy and robust installation (essentially Pypi/conda) so basically what we already have here!

I will add you to pygae now so we can shift the branch there :)

**Comment by hugohadfield** [comment]
@utensil I have shifted my fork of galgebra to pygae and invited you, any chance you could add it as a remote to your local copy and do a PR :) Then we can merge it and have a quick review of the issues and see where we stand!

**Comment by arsenovic** [comment]
hi , i think moving galgebra to pygae is a great idea . @brombo  can submit PR's, and leave the maintenance   to @utensil, (allan if you dont like this, let us know).  i think this will really help galgebra.

### install/deps
using any of the standard numpy/scipy/pandas deps is fine. building a conda package is also a good idea to do eventually.

### docs

i think docs are a big issue that could be improved. galgebra has great docs but not in a sphinx style that people are used to.  its could also use a 'quick start' part for the docs. @utensil , if you look in clifford, we use notebooks with nbsphinx. note that you will need `nbstripout`  so that the output of the notebooks dont fill up your git repo every time you commit. i would be happy to help you get started with this. 

### interoperability
 keeping the syntax as similar as possible is great.  full interoperability i dont think will  work for complex algorithm. 

i would like all the python related GA packages to in pygae, with different teams for each project.

**Comment by utensil** [comment]
> galgebra is good for me because it is symbolic, clifford is good for me because it is numerical.. 
> ...latex formatting... 

Yes, I thought so too.

> I have shifted my fork of galgebra to pygae and invited you, any chance you could add it as a remote to your local copy and do a PR :)

Accepted and thanks. I had added your branch as a remote and trying to merge locally but I need some time to sort things out as there are conflicts and I need to have some tests before deciding how to merge.

**Comment by hugohadfield** [comment]
Sounds great!

**Comment by utensil** [comment]
>  leave the maintenance to @utensil

I can be quite involved, but I can't meet the expectation of a dedicated maintenance due to my busy day-and-night job. 

> if you look in clifford, we use notebooks with nbsphinx...`nbstripout`

Noted. Will work towards this direction when we get there.

>  i would be happy to help you get started with this.

Appreciated :smile: I'll try to set it up as clifford did first see if there're some difficulties.

> full interoperability i dont think will work for complex algorithm.

Yes, just a wish. Let's see how much is good enough.

**Comment by utensil** [comment]
@hugohadfield I noticed pygae/galgebra hasn't enabled Issues, it could be a problem because we can't have discussions there, people can't open issues and commits can't close issues here. Also I don't see the Settings menu in pygae/galgebra, would you help me enable Issues or do you have some other thoughts?

**Comment by utensil** [comment]
The actual work on merge has started at https://github.com/pygae/galgebra/pull/2 , please see there for tasks to be done.

**Comment by hugohadfield** [comment]
Just enabled issues and hopefully fixed your permissions problems @utensil !

**Comment by utensil** [comment]
I'll close this PR as pygae/galgebra#2 is now merged.

**Pull request closed without merging**
