### PR TITLE
Update installation instructions

### LINKED ISSUE #12: 'module' object has no attribute 'Ga'
## Enviroment

* MacBook Pro (Retina, 13-inch, Mid 2014)
* OSX 10.11.2
* Python 2.7.11
* numpy 1.9.2
* sympy 1.0

## Steps

```
git clone https://github.com/brombo/galgebra.git
cd galgebra
python setup.py install
python setup.py test
```

```python
import galgebra
galgebra.Ga
```

## Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Ga'
```

If I `import ga` instead, got

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ga
```

I looked into examples and tests, and can't figure out what went wrong.

### PR DESCRIPTION
**Pull request by utensil**
Fixes #12

### CODE REVIEW

**Comment by utensil** [comment]
A few notes:

* I did not explain `galgebra` is the directory in `galgebra`, which could be confusing but can be realized instantly after the first failure. That said, I still suggest to rename the directory to `src` to avoid such confusion.
* I did not mention the possibility that `site-python` might not exist and the need to create it manually, because I think setgapth.py could easily fix this by adding something like `mkdir -p`.

**Comment by utensil** [comment]
@brombo Is it OK to merge this for now, or should it be obsoleted by #14 ?

**Comment by brombo** [comment]
On 05/11/2016 02:16 AM, Utensil Song wrote:
>
> @brombo <https://github.com/brombo> Is it OK to merge this for now, or 
> should it be obsoleted by #14 
> <https://github.com/brombo/galgebra/issues/14> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/pull/13#issuecomment-218371558>
>
Since my knowledge of git is also limited is there something I need to 
do to merge your changes into my master or what????

**Comment by utensil** [comment]
As the repository owner, you will see something like

image

at the end of this PR(  https://github.com/brombo/galgebra/pull/13 ), right above the comment form.

Click "Merge pull request" and you'll see something like 

image

And then click "Confirm merge".

Then your master branch will merge my commits, and you can do `git pull` locally on your machine.

For a more thorough guide, please see https://help.github.com/articles/merging-a-pull-request/

**Comment by utensil** [comment]
:+1:

**Pull request merged**
